spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mybrary-testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: appleClientId
            client-secret: appleClientSecret
            redirect-uri: appleRedirectUri
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Apple

        provider:
            apple:
                authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
                token-uri: https://appleid.apple.com/auth/token
                user-name-attribute: sub

    sql:
      init:
        mode: never

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    config:
      enabled: false
    aws:
      sns:
        credentials:
          access-key: snsAccessKey
          secret-key: snsSecretKey
        region:
          static: snsRegion
        topic:
          arn: snsTopicArn

logging:
  level:
    root: info

jwt:
  secretKey: testSecretKey