spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mybrary-testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    sql:
      init:
        mode: never

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    config:
      enabled: false

logging:
  level:
    root: info

jwt:
  secretKey: testSecretKey